sudo: true
language: php
php:
  - 7.2
  - 7.3

matrix:
    fast_finish: true
    allow_failures:
      - php: 7.3

branches:
  only:
    - /master/
    - /dev/

before_install:
  - export SCRIPT_DIR=$HOME/islandora/.scripts

install:
  - git clone https://github.com/Islandora/documentation.git $HOME/islandora
  - composer install

script:
  - $SCRIPT_DIR/line_endings.sh $TRAVIS_BUILD_DIR
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: 
    secure: "eOTSJ2E/Q/dJnXCHtxyYxqTheoezNpf0Ssmwu4eaxEqBzS3hf+7T5NllIJzbmcrgQoCNoI3jWfdziyYTdobfXpdBqMHNqigyknzmfbQ0zK23o5GjRH2sx2JRxDf0DAEsPMMG166o+sA3a1qGrjFGKp9x+uVlliesI7/ewVmpQ5ZArmUGbPilwx94WoSPhJfoyOhX5TkaAOQ6x6pxtGGeMwYd8YtDsLtfE0GvkJykH7SvSXPVCtEmHndtECO6kNQpBxkSih+RPra+C//SyvDk8a2oQriymFoHKSTJUgbx2mB8Gs5PtOE/8q+MnQ0T7g6SgP8werHYRAn3F9nk6XGm+iQf48imu1VzTeEYQV/R8Tj8MOcOl6ialZ6GPEJyKYBX50gka0qwKI/MyIQvty9Jm1ZvbJ13kYksSjRSohReBBkZK3E8jadrhufurNkNDbnRmeB49rF5dIi4uQLMZf0jJc+Op0GqBBxumc44t8CnUJqclkrt6vCSiL88jPN1f1BmY3BXhBC1SKcxKR3OMDe1PTsvDl6kwLRKlFDxodYc/wvxCejQ21S00hTeZqYSxmhn7zQwSXmzuBSRpAvz1NUiPrPuEzvP+3Jb+NRD0YJ3o8tcbPQKbwV0xo2yjARx9wBzfTf3Xe7zY07S3kDhhPmeGwAxrePdNdHE5aUFXneMCqo="

