sudo: true
language: php
php:
  - 7.2
  - 7.3

matrix:
    fast_finish: true
    allow_failures:
      - php: 7.3

branches:
  only:
    - /master/
    - /dev/

before_install:
  - export SCRIPT_DIR=$HOME/islandora/.scripts

install:
  - git clone https://github.com/Islandora/documentation.git $HOME/islandora
  - composer install

script:
  - $SCRIPT_DIR/line_endings.sh $TRAVIS_BUILD_DIR
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    rooms:
      secure: "ILyyUBcT0OQI3aLz0QFD1yaDtIyiNEmTHDb05lAgeS3JfAOTPv0UeHjBrQhTwh44gWLew/zD6P6DpMxyw4wRxgEQjUJLu7JEVs7ql9+Q7TE7UBA/QqdupK51eKXRx9iHfWrZuMDM3FLixSBYtZfg/ntRj7rUD3ALVJKPU+vK4LjEXbVxxrcbvmVU87E/gKrG+y4HUgtmxdQuIVQWJOpg5+RGGnk5Siig3HTFqFhCj/W6Y3ECTtO+ZeyNYqS8/+W/jNZY0/WHrZpsiWt0DGWU/rBXrYbTivP/FIBOKXBYSey+Lrt5TOnz2tOlr/rRC7LHG24sDG536MfTQ4MDKzP1dcVbEGozIO9QPuuNfurpQ7SeB8xpuMNQo1rb88gvQ7hD2qmAlm8njUSTbreZT7pBrjcBdkhe2o6x4Z5Fa/1M099u/QYp3CPVGfMrTgmm05kriUZCrVIZPcFee2tXoTxIyJw55ygIvQNZMYzN68sFFbB+Fy9vzN+uP9fi/54X0Zm3mJhii5P+evrPjlOi8/DeD1Hrdib6lUfRDixnArqgja3KTj9dyiI9caesn5qs+7FrD90xq+ix+uU+wCDwYA76Y2zTLvNJyv0VdKtWVITb0rGaC5OBC6dEikw0J5O6INuQDrgF35sxzpa33348OcRDlQ55muSk6w7O35rJsYUJ0DA="
