sudo: true
language: php
php:
  - 7.2
  - 7.3

matrix:
    fast_finish: true
    allow_failures:
      - php: 7.3

branches:
  only:
    - /master/
    - /dev/

before_install:
  - export SCRIPT_DIR=$HOME/islandora/.scripts

install:
  - git clone https://github.com/Islandora/documentation.git $HOME/islandora
  - composer install

script:
  - $SCRIPT_DIR/line_endings.sh $TRAVIS_BUILD_DIR
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    rooms:
      secure: obx9pbOcsx96WuTfxkL560XpACGKROLTL3iSVozRMk6ZlUO7LVA3R3IufMCESqGSB43sQ4A65iuNSdxsIbOxgpsrr+eWfjDKnNhz5G48kwkLmoqOpSZgjgMiy7EWMACUnvmM/oAoxbFf2QyU46PoHx3HxH0HaDE1YrsXKsQdMIsDCHlpwpq3fR2w2KMzKnCu+EbiUROdIRaaoXuhMPThpNmfWmfb7T/nCNVySZTBIvZDr8dmbpruenWcH6s/2iqNOdKS+5hgHJax18QVea41p1GOGDT3uLmMOOsm4VLGw0XUYRIDGOEGSANDsJDj2DlpYPtdrXJOallDKS8KdceuWPaFCw5G0kKo/j5e6tLSWfin8idDiRSM2FBkE1vhMOEzDYZgTL3KdL99X3kq4W4N1gVhYXydotbMym7+1UpXxuec5Ca1T4+GeTLNVk3SGkjiHaWVsItP3PL854mI4Ra7CD9o3pMwOWBpUOcaJwJP0uhKc6TmOpyvK9e+KlAvrhDK8LznCJfTONlWoRI4wTnd2dJTjKRIYXBATxrLcTl2q19BJM0Yh+PKUXKgxAvOuFCuVqq4SfQd8mMD7S42KVpUx0m4MeTpnPwIQWo7VzIayK5kwmfTo30rkfowvrrknhIzYUWXh+dC/w2DOn9O+bpyrKgegvY6yYT5pMXTGr0uNaQ=
